env.TERM = "xterm-256color"

window.opacity = 0.8

window.padding = {x = 10, y = 10}

window.decorations = "Buttonless"
window.blur = true

font.normal = {family = "MesloLGS Nerd Font Mono", style = "Regular"}

font.size = 16

window.option_as_alt = "Both"
